# Hardware decoding
hwdec=auto-safe

# Нормальный современный GPU output
vo=gpu-next

# Wayland
gpu-context=wayland

# Субтитры
sub-auto=fuzzy
sub-font-size=42

# Не закрывать окно сразу после окончания
keep-open=yes

# Нормальная синхронизация
video-sync=display-resample

# Screenshot
screenshot-format=png
