music_directory          "~/Music"
playlist_directory       "~/.local/state/mpd/playlists"

db_file                  "~/.local/state/mpd/database"
state_file               "~/.local/state/mpd/state"
sticker_file             "~/.local/state/mpd/sticker.sql"

# Только локальные подключения.
bind_to_address           "127.0.0.1"
port                      "6600"

# Не публиковать MPD через Avahi/Bonjour.
zeroconf_enabled          "no"

# Не позволяем symlink из ~/Music вести куда-то ещё.
follow_outside_symlinks   "no"

# При запуске не начинать внезапно воспроизводить музыку.
restore_paused            "yes"

audio_output {
    type                  "pulse"
    name                  "PipeWire"
    mixer_type            "software"
}

auto_update               "yes"

audio_output {
    type   "fifo"
    name   "Visualizer feed"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}
